version: "3.8"
services:
  frontend:
    container_name: frontend_development
    build:
      context: .
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BE_URL=${NEXT_PUBLIC_BE_URL}
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      #- WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
