version: "3.8"
services:
  frontend:
    container_name: frontend_production
    build: .
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BE_URL=${NEXT_PUBLIC_BE_URL}
    ports:
      - 3000:3000
